/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type IntegritetspolicyPage = {
  _id: string;
  _type: "integritetspolicyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  sections?: Array<
    {
      _key: string;
    } & PageSection
  >;
};

export type VillkorPage = {
  _id: string;
  _type: "villkorPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  sections?: Array<
    {
      _key: string;
    } & PageSection
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type OmOssPage = {
  _id: string;
  _type: "omOssPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  subheading?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  badges?: Array<string>;
  visionHeading?: string;
  visionParagraphs?: Array<string>;
  benefitsHeading?: string;
  benefits?: Array<{
    title?: string;
    description?: string;
    _type: "benefit";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading?: string;
  headingItalic?: string;
  body?: string;
  ctaLabel?: string;
  ctaHref?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PageSection = {
  _type: "pageSection";
  heading?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | IntegritetspolicyPage
  | VillkorPage
  | SanityImageAssetReference
  | OmOssPage
  | SanityImageCrop
  | SanityImageHotspot
  | Hero
  | PageSection
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: HERO_QUERY
// Query: *[_type == "hero" && _id == "hero"][0]
export type HERO_QUERY_RESULT = {
  _id: "hero";
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading?: string;
  headingItalic?: string;
  body?: string;
  ctaLabel?: string;
  ctaHref?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: OM_OSS_QUERY
// Query: *[_type == "omOssPage" && _id == "omOssPage"][0]
export type OM_OSS_QUERY_RESULT = {
  _id: "omOssPage";
  _type: "omOssPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  subheading?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  badges?: Array<string>;
  visionHeading?: string;
  visionParagraphs?: Array<string>;
  benefitsHeading?: string;
  benefits?: Array<{
    title?: string;
    description?: string;
    _type: "benefit";
    _key: string;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: VILLKOR_QUERY
// Query: *[_type == "villkorPage" && _id == "villkorPage"][0]
export type VILLKOR_QUERY_RESULT = {
  _id: "villkorPage";
  _type: "villkorPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  sections?: Array<
    {
      _key: string;
    } & PageSection
  >;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: INTEGRITETSPOLICY_QUERY
// Query: *[_type == "integritetspolicyPage" && _id == "integritetspolicyPage"][0]
export type INTEGRITETSPOLICY_QUERY_RESULT = {
  _id: "integritetspolicyPage";
  _type: "integritetspolicyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  sections?: Array<
    {
      _key: string;
    } & PageSection
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "hero" && _id == "hero"][0]': HERO_QUERY_RESULT;
    '*[_type == "omOssPage" && _id == "omOssPage"][0]': OM_OSS_QUERY_RESULT;
    '*[_type == "villkorPage" && _id == "villkorPage"][0]': VILLKOR_QUERY_RESULT;
    '*[_type == "integritetspolicyPage" && _id == "integritetspolicyPage"][0]': INTEGRITETSPOLICY_QUERY_RESULT;
  }
}
